name: Generate Nordic Countries

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - country: "sweden"
            admin_level_1: "Sverige"
            admin_level_2: "Stockholms län"
            admin_level_3: "Stockholms kommun"
          - country: "norway"
            admin_level_1: "Norge"
            admin_level_2: "Vestland"
            admin_level_3: "Bergen"
          - country: "finland"
            admin_level_1: "Suomi / Finland"
            admin_level_2: "Varsinais-Suomi"
            admin_level_3: "Turku"
          - country: "denmark"
            admin_level_1: "Danmark"
            admin_level_2: "Region Midtjylland"
            admin_level_3: "Aarhus Kommune"
          - country: "iceland"
            admin_level_1: "Ísland"
            admin_level_2: "Höfuðborgarsvæðið"
            admin_level_3: "Reykjavíkurborg"

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Cache downloaded OSM files
        uses: actions/cache@v3
        id: cache-${{ matrix.country }}
        with:
          path: "*.osm.pbf"

      - name: Download OSM data
        run: >-
          wget https://download.geofabrik.de/europe/${{ matrix.country }}-latest.osm.pbf
          -O europe-${{ matrix.country }}.osm.pbf

  #     - name: Process data
  #       run: >-
  #         python3
  #         build_db.py
  #         europe-${{ matrix.country }}.osm.pbf
  #         europe-${{ matrix.country }}.json.db
  #         --alfa "${{ matrix.admin_level_1 }}"
  #         --beta "${{ matrix.admin_level_2 }}"
  #         --gamma "${{ matrix.admin_level_3 }}"
  #     - name: Active outout
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: nordic-countries
  #         path: europe-${{ matrix.country }}.json.db
  # assemble:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: List files
