name: Generate Nordic Countries

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - country: "sweden"
            admin_level_1: 2
            admin_level_2: 4
            admin_level_3: 7
          - country: "norway"
            admin_level_1: 2
            admin_level_2: 4
            admin_level_3: 7
          - country: "finland"
            admin_level_1: 2
            admin_level_2: 4
            admin_level_3: 7
          - country: "denmark"
            admin_level_1: 2
            admin_level_2: 4
            admin_level_3: 7
          - country: "iceland"
            admin_level_1: 2
            admin_level_2: 4
            admin_level_3: 7

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Download OSM data
        run: wget https://download.geofabrik.de/europe/${{ matrix.country }}-latest.osm.pbf -O europe-${{ matrix.country }}.osm.pbf
      - name: Process data
        run: python3 build_db.py europe-${{ matrix.country }}.osm.pbf europe-${{ matrix.country }}.json.db -a ${{ matrix.admin_level_1 }} -b ${{ matrix.admin_level_2 }} -c ${{ matrix.admin_level_3 }}
      - name: Active outout
        uses: actions/upload-artifact@v3
        with:
          name: nordic-countries
          path: europe-${{ matrix.country }}.json.db
