name: Generate Nordic Countries

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      max-parallel: 8
      matrix:
        include:
          - country: "Sweden"
            alfa: "Sverige"
            beta: "Stockholms län"
            gamma: "Stockholms kommun"
            osm_source_file: "https://download.geofabrik.de/europe/sweden-latest.osm.pbf"

          - country: "Norway"
            alfa: "Norge"
            beta: "Vestland"
            gamma: "Bergen"
            osm_source_file: "https://download.geofabrik.de/europe/norway-latest.osm.pbf"

          - country: "Finland"
            alfa: "Suomi / Finland"
            beta: "Varsinais-Suomi"
            gamma: "Turku"
            osm_source_file: "https://download.geofabrik.de/europe/finland-latest.osm.pbf"

          - country: "Denmark"
            alfa: "Danmark"
            beta: "Region Midtjylland"
            gamma: "Aarhus Kommune"
            osm_source_file: "https://download.geofabrik.de/europe/denmark-latest.osm.pbf"

          - country: "Iceland"
            alfa: "Ísland"
            beta: "Höfuðborgarsvæðið"
            gamma: "Reykjavíkurborg"
            osm_source_file: "https://download.geofabrik.de/europe/iceland-latest.osm.pbf"

    uses: "./.github/workflows/generate.yaml"
    with:
      country: "${{ matrix.country }}"
      alfa: "${{ matrix.alfa }}"
      beta: "${{ matrix.beta }}"
      gamma: "${{ matrix.gamma }}"
      osm_source_file: "${{ matrix.osm_source_file }}"
      artifact: "nordic-countries"
