name: Generate Nordic Countries

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - country: "sweden"
            ADMIN_LEVEL_1: 2
            ADMIN_LEVEL_2: 4
            ADMIN_LEVEL_3: 7
          # - country: "norway"
          #   ADMIN_LEVEL_1: 2
          #   ADMIN_LEVEL_2: 4
          #   ADMIN_LEVEL_3: 7
          # - country: "finland"
          #   ADMIN_LEVEL_1: 2
          #   ADMIN_LEVEL_2: 4
          #   ADMIN_LEVEL_3: 7
          # - country: "denmark"
          #   ADMIN_LEVEL_1: 2
          #   ADMIN_LEVEL_2: 4
          #   ADMIN_LEVEL_3: 7
          # - country: "iceland"
          #   ADMIN_LEVEL_1: 2
          #   ADMIN_LEVEL_2: 4
          #   ADMIN_LEVEL_3: 7

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Download OSM data
        run: wget https://download.geofabrik.de/europe/${{ matrix.country }}-latest.osm.pbf -O europe-${{ matrix.country }}.osm.pbf
      - name: Process data
        run: python3 build_db.py europe-${{ matrix.country }}.osm.pbf europe-${{ matrix.country }}.osm.pbf
      - name: Active outout
        uses: actions/upload-artifact@v3
        with:
          name: nordic-countries
          path: europe-${{ matrix.country }}.osm.pbf
