name: Generate Nordic Countries

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 8
      matrix:
        include:
          - country: "Sweden"
            alfa: "Sverige"
            beta: "Stockholms län"
            gamma: "Stockholms kommun"
            osm_source_file: "https://download.geofabrik.de/europe/sweden-latest.osm.pbf"

          - country: "Norway"
            alfa: "Norge"
            beta: "Vestland"
            gamma: "Bergen"
            osm_source_file: "https://download.geofabrik.de/europe/norway-latest.osm.pbf"

          - country: "Finland"
            alfa: "Suomi / Finland"
            beta: "Varsinais-Suomi"
            gamma: "Turku"
            osm_source_file: "https://download.geofabrik.de/europe/finland-latest.osm.pbf"

          - country: "Denmark"
            alfa: "Danmark"
            beta: "Region Midtjylland"
            gamma: "Aarhus Kommune"
            osm_source_file: "https://download.geofabrik.de/europe/denmark-latest.osm.pbf"

          - country: "Iceland"
            alfa: "Ísland"
            beta: "Höfuðborgarsvæðið"
            gamma: "Reykjavíkurborg"
            osm_source_file: "https://download.geofabrik.de/europe/iceland-latest.osm.pbf"

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Download OSM data
        run: wget ${{ matrix.osm_source_file }} -O europe-${{ matrix.country }}.osm.pbf

      - name: Process data
        run: >-
          python3 build_db.py europe-${{ matrix.country }}.osm.pbf europe-${{ matrix.country }}.json.db
          --alfa "${{ matrix.alfa }}" --beta "${{ matrix.beta }}" --gamma "${{ matrix.gamma }}"

      - name: Active outout
        uses: actions/upload-artifact@v3
        with:
          name: nordic-countries
          path: europe-${{ matrix.country }}.json.db

  assemble:
    name: "Assemble"
    needs: build
    uses: .github/workflows/world.yaml@master
    with:
      artifact: nordic-countries

  simplify:
    uses: .github/workflows/simplify.yaml@master
    needs: assemble
    with:
      artifact: nordic-countries
