name: Generate Extracts

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      max-parallel: 8
      matrix:
        include:

          #
          # List of extracts to process
          #

          - country: "Sweden"
            alfa: "Sverige"
            beta: "Stockholms län"
            gamma: "Stockholms kommun"
            osm_source_file: "https://download.geofabrik.de/europe/sweden-latest.osm.pbf"

          - country: "Norway"
            alfa: "Norge"
            beta: "Vestland"
            gamma: "Bergen"
            osm_source_file: "https://download.geofabrik.de/europe/norway-latest.osm.pbf"

          - country: "Finland"
            alfa: "Suomi / Finland"
            beta: "Varsinais-Suomi"
            gamma: "Turku"
            osm_source_file: "https://download.geofabrik.de/europe/finland-latest.osm.pbf"

          - country: "Denmark"
            alfa: "Danmark"
            beta: "Region Midtjylland"
            gamma: "Aarhus Kommune"
            osm_source_file: "https://download.geofabrik.de/europe/denmark-latest.osm.pbf"

          - country: "Iceland"
            alfa: "Ísland"
            beta: "Höfuðborgarsvæðið"
            gamma: "Reykjavíkurborg"
            osm_source_file: "https://download.geofabrik.de/europe/iceland-latest.osm.pbf"

          #
          # End of list
          #

    uses: "./.github/workflows/build.yaml"
    with:
      country: "${{ matrix.country }}"
      alfa: "${{ matrix.alfa }}"
      beta: "${{ matrix.beta }}"
      gamma: "${{ matrix.gamma }}"
      osm_source_file: "${{ matrix.osm_source_file }}"
      artifact: "database"

  generate-world:
    name: "Generate World"
    needs: generate-build
    uses: ./.github/workflows/world.yaml
    with:
      artifact: "database"

  generate-simplify:
    name: "Simplify"
    needs: generate-world
    uses: ./.github/workflows/simplify.yaml
    with:
      artifact: "database"
